    name: Image to Json Generation
    
    on:
      push:
        branches: [ master ]
      schedule:
        - cron: '0 0 1 * *' #runs at 00:00 UTC everyday
    
    jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: execute py script # run the run.py to get the latest data
            run: |
              python json_creator.py
          - name: switching from HTTPS to SSH
            run: git remote set-url origin ${{ secrets.ssh }}
          - name: check for changes
            run: git status
          - name: stage changed files
            run: git add .
          - name: commit changed files
            run: git commit -m "Auto updating img_data.json"
          - name: fetch from master
            run: git fetch origin master
          - name: push code to master
            run: git push origin HEAD:master
