    name: Image to Json Generation
    
    on:
      push:
        branches: [ master ]
      schedule:
        - cron: '0 0 1 * *' #runs at 00:00 UTC everyday
    
    jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: execute py script # run the run.py to get the latest data
            run: |
              python json_creator.py
          - name: Commit files # transfer the new html files back into the repository
            run: |
                git config --local user.name "Image to Json Generation Action"
                git add ./img_data.json
                git commit -m "Auto Updating the img_data.json"
          - name: Push changes # push the output folder to your repo
            uses: ad-m/github-push-action@master
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                force: true
